  image: alpine-python3.6
  test:
    script:
    - apk --update add git openssh pip3 libffi libxslt libxml2 opus python3.6
  # - sudo apt-get install libffi-dev libxslt-dev libxml2-dev libopus0
    - pip install -r requirements.txt
    - make test
