  image: frolvlad/alpine-python3
  test:
    script:
    - apk --update add git openssh libffi libxslt libxml2 opus make gcc
  # - sudo apt-get install libffi-dev libxslt-dev libxml2-dev libopus0
    - pip install -r requirements.txt
    - make test
