language: python
install:
  - sudo apt-get install libffi-dev libxslt-dev libxml2-dev libopus0
  - pip install -r requirements.txt
  - cp tests/configs ./
python:
  - 3.6
script:
  - make test
cache:
  - pip

